apiVersion: v1
kind: Pod
metadata:
  name: dev-nginx-pod
  labels:
    name: dev-nginx-pod
spec:
  containers:
  - name: dev-nginx-pod
    image: nginx:latest
    resources:
      limits:
        memory: "64Mi"
        cpu: "250m"