apiVersion: v1
kind: Pod
metadata:
  namespace: xfusion
  name: time-check
  labels:
    name: time-check
spec:
  containers:
  - name: time-check
    image: busybox:latest
    command:
      - /bin/sh
      - -c
      - |
        while true; do
          date >> /opt/sysops/time/time-check.log
          sleep $TIME_FREQ
        done
    envFrom:
    - configMapRef:
        name: time-config
    volumeMounts:
    - mountPath: /opt/sysops/time
      name: log-volume
    resources:
      limits:
        memory: "64Mi"
        cpu: "250m"
  volumes:
  - name: log-volume
    emptyDir: 
      sizeLimit: 50Mi
      medium: Memory